DEFINE_ACTION_FUNCTION unsummon
BEGIN
  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "rr#usumn.bam"
    location	= "graphics"
    locbase
  END

  LAUNCH_ACTION_FUNCTION install_spell
    STR_VAR
    spell	= "mh#unsum"
    location	= "spells"
    locbase
    editstring	= "say_name=>0"
  END

  MAKE_PATCH
    match=>"gender = summoned"
    add_spells=>"mh#unsum"
  END
    
  LAUNCH_ACTION_FUNCTION edit_all_creatures
    STR_VAR
    edits	= "patch_data"
  END
END	// unsummon


