DEFINE_ACTION_FUNCTION setup_restorations
BEGIN
  LAUNCH_ACTION_FUNCTION check_ini
    STR_VAR
    ini		= "recycle_unused_idsnames"
    RET
    recycle_unused_idsnames	= value
  END


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "install_restorations restorations_postproc"
    tra		= "restorations"
  END

  ACTION_IF recycle_unused_idsnames AND NOT is_eet
  BEGIN
    LAUNCH_ACTION_FUNCTION run
      STR_VAR
      file	= "recycle_unused_idsnames"
    END
  END
END	// restorations


