DEFINE_ACTION_FUNCTION setup_divine_spells
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "divine_resources"
  END
 
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "summoned_monsters"
    tra		= "summoned_monsters"
    locbase	= "shared"
  END
 
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "divine_core"
    tra		= "divine_core"
  END
 
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "divine_aftercare"
  END
END	// setup_divine_spells


