DEFINE_ACTION_FUNCTION ranger_postproc
BEGIN
  // 3.5e-stype spell table

  COPY "%MOD_FOLDER%/%component_loc%/tables/mxsplran.2da" "override"


  // Make ranger's Charm Animal better with level

  spl.edit[%RANGER_CHARM_ANIMAL%]
  [
    m.ab.delete{s_level>1}
    m.ab.clone{s_level=entry_index*2+1|number:i=10}
    m.ab_fx.alter{s_savebonus=(p_level < 3)?0:(0 - ((p_level - 1) / 2))|match="s_save_vs_spell=1"}
  ]
END	// ranger_postproc


