DEFINE_ACTION_FUNCTION epic_compat
BEGIN
  ACTION_IF NOT enhanced_edition
  BEGIN
    // Iolaum's Longevity
    //
    // oBG2 did not have a save for half damage flag

    spl.edit[mh#iolla]
    [
      m.adfx.alter{s_dicenumber/=2|match="opcode=12"}
      m.adfx.clone{s_dicenumber+=(p_level MODULO 2) s_save_vs_spell=0 s_save_vs_breath=0 s_save_vs_poison=0 s_save_vs_wand=0 s_save_vs_polymorph=0|match="s_opcode=12"}
    ]
  END
END	// epic_compat


