DEFINE_ACTION_FUNCTION setup_epic_spellpack
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "epic_preproc"
  END


  LAUNCH_ACTION_FUNCTION grand_unified_installer
    STR_VAR
    copy_files	= ""
    tra		= "epic_spellpack"
  END

  LAM data_spell_resrefs


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "arcane_hla_tables divine_hla_tables epic_postproc epic_compat"
    tra		= "epic_spellpack"
  END
END	// setup_epic_spellpack


