DEFINE_ACTION_FUNCTION animate_dead_postproc
BEGIN
  MAKE_PATCH
    clone_item_inline'1=>~match=>"item_resource = scrl2d" item_resource=>"mh#ad4th" state_identified=>1 clone_above=>1~
    clone_item_inline'2=>~match=>"item_resource = scrl2d" item_resource=>"mh#ad7th" state_identified=>1 item_num_in_stock=>1~
  END

  LAUNCH_ACTION_FUNCTION edit_all_stores
    STR_VAR
    edits	= "patch_data"
  END
END	// animate_dead_postproc


