DEFINE_ACTION_FUNCTION level_4_animate_dead
BEGIN
  WIZARD_ANIMATE_DEAD_4TH,WIZARD_ANIMATE_DEAD_4TH_SCROLL=spl.copy[%WIZARD_ANIMATE_DEAD%=>WIZARD_ANIMATE_DEAD_4TH]
  [
    m_level = 4
    m.ab_fx.alter{s_power = 4|match="s_power > 0"}
    m_description = m_description.patch{REPLACE_TEXTUALLY EXACT_MATCH ": 5" ": 4"}
  ]

  COPY_EXISTING "%WIZARD_ANIMATE_DEAD%a.bam" "override/%WIZARD_ANIMATE_DEAD_4TH%a.bam"
                "%WIZARD_ANIMATE_DEAD%b.bam" "override/%WIZARD_ANIMATE_DEAD_4TH%b.bam"
                "%WIZARD_ANIMATE_DEAD%c.bam" "override/%WIZARD_ANIMATE_DEAD_4TH%c.bam"
END	// level_4_animate_dead


