DEFINE_ACTION_FUNCTION level_5_ghoul_call
BEGIN
  ACTION_IF NOT FILE_EXISTS_IN_GAME "ghoulsu.eff"
  BEGIN
    eff.make["ghoulsu"]
    [
      m_opcode = 67
      m_target = 1
      m_timing = 1
      m_parameter2 = 1
      m_power = 5
      m_resource := "ghoulsu"
      m_resource2 := "spraised"
    ]
  END

  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcala.bam" "override"
  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcalb.bam" "override"
  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcalc.bam" "override"

  spl.edit[%WIZARD_ANIMATE_DEAD%]
  [
    m_name:=@0
    m_description:=@1
    m_icon:="mh#gcalc"
    m.ab.delete{(s_level MODULO 2)=0}
    m.ab.alter{s_icon:="mh#gcalb"}
    m.ab_fx.delete{s_opcode=177}
    m.ab_fx.add{s_opcode=177 s_target=1 s_duration=2400 s_parameter2=2 s_power=5 s_resource:=ghoulsu|number:i=3}
  ]

  itm.edit[scrl2d]
  [
    m_identified_name:=@0
    m_identified_description:=@1
    m_icon:="mh#gcala"
    m.ab.alter{s_icon:="mh#gcala"}
  ]
END	// level_5_ghoul_call


