DEFINE_ACTION_FUNCTION setup_animate_dead
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "animate_dead_preproc"
    tra		= "animate_dead"
  END

  LAUNCH_ACTION_FUNCTION grand_unified_installer
    STR_VAR
    copy_files	= ""
    tra		= "animate_dead"
  END

  OUTER_SET macro_spellcodes_read=0
  LAUNCH_ACTION_MACRO read_in_spellcodes

/*
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "animate_dead_postproc"
    tra		= "summoning"
  END
*/
END	// setup_animate_dead


