DEFINE_ACTION_FUNCTION level_4_animate_dead
BEGIN
  LAUNCH_ACTION_FUNCTION clone_spell
    STR_VAR
    spell	= "spwi501=>mh#lv4ad"
    editstring	= ~level=>4 substitute_description=>"5=>4"~
  END


  LAUNCH_ACTION_FUNCTION edit_item
    STR_VAR
    item	= "scrl2d"
    editstring	= ~price=>500 substitute_description=>"5=>4" patch_effect_inline=>"resource=>mh#lv4ad"~
  END
END	// level_4_animate_dead


