DEFINE_ACTION_FUNCTION level_4_animate_dead
BEGIN
  WIZARD_ANIMATE_DEAD_4TH,WIZARD_ANIMATE_DEAD_4TH_SCROLL=spl.copy[%WIZARD_ANIMATE_DEAD%=>WIZARD_ANIMATE_DEAD_4TH]
  [
    m_level=4
    m.ab_fx.alter{s_power=4}
  ]

  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcala.bam" "override"
  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcalb.bam" "override"
  COPY "%MOD_FOLDER%/%component_loc%/graphics/mh#gcalc.bam" "override"

  spl.edit[%WIZARD_ANIMATE_DEAD%]
  [
    m_name:=@13
    m_description:=@14
    m_icon:="mh#gcalc"
    m.ab.delete{(s_level MODULO 2)=0}
    m.ab.alter{s_icon:="mh#gcalb"}
    m.ab_fx.delete{s_opcode=177}
    m.ab_fx.add{s_opcode=177 s_target=1 s_duration=2400 s_parameter2=2 s_power=5 s_resource:=ghoulsu|number:i=3}
  ]

  itm.edit[scrl2d]
  [
    m_identified_name:=@13
    m_identified_description:=@14
  ]


  COPY_EXISTING_REGEXP "^.+\.sto$" "override"
    PATCH_IF INDEX_BUFFER (CASE_INSENSITIVE "scrl2d")
    BEGIN
      LAUNCH_PATCH_FUNCTION struct_read RET_ARRAY m = struct END
      LAUNCH_PATCH_FUNCTION struct_clone
        STR_VAR
        type	= item
        struct	= m
        match	= ~s_resref=="scrl2d"~
        patch	= ~s_resref:="%WIZARD_ANIMATE_DEAD_4TH_SCROLL%"~
        RET_ARRAY
	m	= struct
      END
      LAUNCH_PATCH_FUNCTION struct_write STR_VAR struct = m END
    END

    BUT_ONLY_IF_IT_CHANGES
END	// level_4_animate_dead


