DEFINE_ACTION_FUNCTION divine_preproc
BEGIN
  // Create mistposu.cre if we don't have it yet.

  ACTION_IF NOT FILE_EXISTS_IN_GAME "mistposu.cre"
  BEGIN
    cre.copy[mistpo01=>mistposu]
    [
      m_xp_value:=0
      m_gender:=summoned
    ]

    cre.edit[mistpo01]
    [
      m_xp_value:=3500
      m_gender:=neither
    ]

    eff.edit[sppois]
    [
      m_resource:="mistposu"
    ]
  END
END	// divine_preproc


