DEFINE_ACTION_FUNCTION setup_divine_spellpack
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "divine_preproc"
    tra		= "divine_spellpack"
  END


  LAUNCH_ACTION_FUNCTION grand_unified_installer
    STR_VAR
    tra		= "divine_spellpack"
  END

  LAM data_spell_resrefs


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "divine_postproc divine_compat"
    tra		= "divine_spellpack"
  END
END	// setup_divine_spellpack


