DEFINE_ACTION_FUNCTION paladin_resources
BEGIN
  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    files	= "all"
    location	= "graphics"
    postfix	= "bam"
  END


  // Create damage effects

  OUTER_FOR (SET i = 1; i <= 11; ++i)
  BEGIN
    CREATE EFF "mh#m%i%d6"
      WRITE_LONG	0x0010 12	// HP: Damage
      WRITE_LONG	0x0020 4194304	// Magic
      WRITE_SHORT	0x0024 1
      WRITE_LONG	0x002c 100
      WRITE_LONG	0x0038 i
      WRITE_LONG	0x003c 6
  END
END	// paladin_resources


