DEFINE_ACTION_FUNCTION paladin_resources
BEGIN
  // Graphical resources

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    files	= "all"
    location	= "graphics"
    postfix	= "bam"
  END


  // Create smite damage effects

  OUTER_FOR (SET i = 1; i <= 11; ++i)
  BEGIN
    LAUNCH_ACTION_FUNCTION make_effect
      STR_VAR
      effect		= "mh#m%i%d6"
      editstring	= "opcode=>12 target=>2 timing=>1 parameter2=>4194304 dicenum=>%i% dicesize=>6"
    END
  END
END	// paladin_resources


