DEFINE_ACTION_FUNCTION setup_bard_powers
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bard_preproc"
    tra		= "bard_powers"
  END

  LAUNCH_ACTION_FUNCTION grand_unified_installer
    STR_VAR
    copy_files	= ""
    tra		= "bard_powers"
  END

  OUTER_SET macro_spellcodes_read=0
  LAUNCH_ACTION_MACRO read_in_spellcodes

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bard_kit_tables"
    tra		= "bard_powers"
  END
END	// setup_bard_powers


