DEFINE_ACTION_FUNCTION setup_bard_powers
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bard_preproc"
    tra		= "bard_powers"
  END


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "arcane_healing"
    locbase	= "shared/spells"
  END


  LAUNCH_ACTION_MACRO data_spell_resrefs


  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "bard_kit_tables"
    tra		= "bard_powers"
  END
END	// setup_bard_powers


